#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable


layout(binding = 0, set = 0, std430) buffer data_buffer { uint data[]; };

layout (constant_id = 0) const int MULTIPLIER = 0;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    ivec2 ipos = ivec2(gl_GlobalInvocationID);
    debugPrintfEXT("%d", data[ipos.x]);
    data[ipos.x] = data[ipos.x] * MULTIPLIER;
}